### ISSUE TITLE
Support for mongoDB

### ISSUE THREAD

**Issue by matrixbegins** [pinax/pinax-project-account#17]
HI Just had two little questions, Quite new to python and Django actually.

1. If the adapter for Database cloud be changed to mongoDB, will the site work instead of sqlite3?

2. Do you have any default credentials already for loggin in?

**Comment by jtauber** [comment]
1. Most of Pinax should be agnostic as to database backend but no idea what the state of Django and MongoDB is, sorry.

2. No, there are no default credentials and it's probably dangerous to have them in case people forget to turn them off.
